In [1]:
import re 
import os
import ast
import time
import sqlite3
import requests
import numpy as np
import pandas as pd
import scrape_functions 
from dotenv import load_dotenv 
from nba_api.stats.endpoints import draftcombinestats
from nba_api.stats.endpoints import draftcombinedrillresults

---
### Data Collection
---

In [ ]:
# combine_stats = []
# drill_results = []

# for year in range(2015, 2027):
#     combine_stat = (
#         draftcombinestats
#         .DraftCombineStats(league_id='00', season_all_time=f'{year}')
#         .get_data_frames()
#         [0]
#     )
#     combine_drill_results = (
#         draftcombinedrillresults
#         .DraftCombineDrillResults(league_id='00', season_year=f'{year}')
#         .get_data_frames()
#         [0]
#     )

#     combine_stats.append(combine_stat)
#     drill_results.append(combine_drill_results)

# player_stats = pd.concat(combine_stats, axis=0)
# drill_stats = pd.concat(drill_results, axis=0)

# player_stats = player_stats.dropna(axis=1, thresh=700)

# df = player_stats.merge(drill_stats, on=['PLAYER_ID', 'FIRST_NAME', 'LAST_NAME', 'PLAYER_NAME'], how='outer')

# conn = sqlite3.connect("nba.db")

# df.to_sql(
#     "combine_stats",
#     conn,
#     if_exists="replace",
#     index=False
# )

# conn.close()

In [36]:
with sqlite3.connect('nba.db') as conn:
    ncaa_stats = pd.read_sql_query(
        'SELECT * FROM "combine_stats"',
        conn
    )

ncaa_stats.head()

,SEASON,PLAYER_ID,FIRST_NAME,LAST_NAME,PLAYER_NAME,POSITION_x,HEIGHT_WO_SHOES,HEIGHT_WO_SHOES_FT_IN,WEIGHT,WINGSPAN,...,HAND_LENGTH,HAND_WIDTH,TEMP_PLAYER_ID,POSITION_y,STANDING_VERTICAL_LEAP,MAX_VERTICAL_LEAP,LANE_AGILITY_TIME,MODIFIED_LANE_AGILITY_TIME,THREE_QUARTER_SPRINT,BENCH_PRESS
0,2015,2006,Larry,Nance,Larry Nance,PF,79.50,6' 7.5'',226.6,85.50,...,9.00,9.75,15038,PF,29.0,37.5,10.93,3.01,3.25,10.0
1,2016,204211,Justin,Jackson,Justin Jackson,SF,79.00,6' 7'',193.4,82.75,...,8.75,8.75,16030,SF,29.5,34.5,11.32,2.96,3.26,NaN
2,2015,204456,TJ,McConnell,TJ McConnell,PG,72.50,6' 0.5'',187.8,74.00,...,7.50,7.00,15035,PG,26.0,31.5,10.95,3.09,3.30,7.0
3,2015,1626145,Tyus,Jones,Tyus Jones,PG,72.50,6' 0.5'',184.6,77.00,...,8.25,8.75,15030,PG,26.5,32.5,11.84,2.95,3.32,2.0
4,2015,1626146,Cliff,Alexander,Cliff Alexander,PF-C,79.25,6' 7.25'',239.2,87.50,...,9.50,10.25,15000,PF-C,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
# load_dotenv()
# API_KEY = os.getenv('CBB_DATA_API_KEY')

# data = {}
# for year in range(2015, 2027):
#     CBB_URL = f'https://api.collegebasketballdata.com/stats/player/season?season={year}'

#     headers = {
#         "Authorization": f"Bearer {API_KEY}",
#         "Accept": "application/json",
#         "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
#     }

#     params = {
#         "year": year          # Specify the basketball season year
#     }


#     try:
#         print("Sending API request...")
#         response = requests.get(CBB_URL, headers=headers, params=params)
        
#         print(f"Server Status Code: {response.status_code}")
#         content_type = response.headers.get("Content-Type", "")
#         print(f"Response Content Type: {content_type}")
        
#         if response.status_code == 200:
#             # Check if the text matches valid JSON architecture
#             if "application/json" in content_type:
#                 player_stats = response.json()

#                 data[year] = player_stats
#                 print(f"Success! Parsed {len(player_stats)} player records.")
#             else:
#                 print("\n⚠️ WARNING: Server responded with status 200, but data is NOT JSON.")
#                 print("--- RAW SERVER DATA PREVIEW ---")
#                 print(response.text[:800]) # Look directly at what the platform returned
#                 print("-------------------------------")
                
#     except requests.exceptions.RequestException as e:
#         print(f"Network error occurred: {e}")
#     except Exception as e:
#         print(f"An unexpected parsing issue occurred: {e}")

# dict_cols = [
#     "fieldGoals",
#     "twoPointFieldGoals",
#     "threePointFieldGoals",
#     "freeThrows",
#     "rebounds",
#     "winShares"
# ]

# def to_dict(x):
#     if isinstance(x, dict):
#         return x
#     if pd.isna(x):
#         return {}
#     return ast.literal_eval(x)

# for year in data.keys():

#     college_data = {}

#     for item in data[year]:
#         for key, value in item.items():
#             college_data[key] = []

#     for item in data[year]:
#         for key, value in item.items():
#             college_data[key].append(value)
            
#     df = pd.DataFrame(college_data)
    
#     # fixing columns that contain dictionary entries
#     for col in dict_cols:
#         df[col] = df[col].apply(to_dict)

#         expanded = pd.json_normalize(df[col]).add_prefix(f"{col}_")

#         df = pd.concat(
#             [df.drop(columns=[col]).reset_index(drop=True),
#             expanded.reset_index(drop=True)],
#             axis=1
#         )

#     data[year] = df 

# combined_df = pd.concat(
#     [
#         df.assign(year=year)
#         for year, df in data.items()
#     ],
#     ignore_index=True
# )

# conn = sqlite3.connect("nba.db")

# combined_df.to_sql(
#     "ncaa_stats",
#     conn,
#     if_exists="replace",
#     index=False
# )

# conn.close()

In [5]:
with sqlite3.connect('nba.db') as conn:
    ncaa_stats = pd.read_sql_query(
        'SELECT * FROM "ncaa_stats"',
        conn
    )

ncaa_stats.head()

,season,seasonLabel,teamId,team,conference,athleteId,athleteSourceId,name,position,games,...,freeThrows_attempted,freeThrows_pct,rebounds_offensive,rebounds_defensive,rebounds_total,winShares_offensive,winShares_defensive,winShares_total,winShares_totalPer40,year
0,2015,20142015,1,Abilene Christian,Southland,47237,3152345,K.J. Maura,G,17,...,5,100.0,7,17,24,0.1,0.1,0.2,0.041,2015
1,2015,20142015,1,Abilene Christian,Southland,47386,3152349,Drake Green,G,28,...,16,56.3,4,18,22,-0.4,0.1,-0.3,-0.049,2015
2,2015,20142015,1,Abilene Christian,Southland,47387,3152347,Isaiah Tripp,G,29,...,25,60.0,13,20,33,0.2,0.1,0.3,0.057,2015
3,2015,20142015,1,Abilene Christian,Southland,52198,67296,Christian Albright,F,20,...,17,64.7,21,44,65,-0.2,0.3,0.1,0.015,2015
4,2015,20142015,1,Abilene Christian,Southland,56233,3155902,Duran Porter,F,31,...,40,50.0,29,42,71,-0.1,0.2,0.1,0.010,2015

In [89]:
# draft_data = []

# for year in range(2015, 2026):
#     url = f'https://www.basketball-reference.com/draft/NBA_{year}.html'

#     soup = scrape_functions.get_soup(url=url)

#     tbodies = soup.find_all("tbody")

#     tables = {}

#     for i, tbody in enumerate(tbodies):
#         rows_data = []
#         table_name = None

#         for row in tbody.find_all("tr"):
#             row_id = row.get("id")

#             if row_id and table_name is None:
#                 table_name = row_id.split(".")[0]

#             cells = row.find_all(["th", "td"])

#             row_dict = {}
#             for j, cell in enumerate(cells):
#                 col_name = cell.get("data-stat")
#                 text = cell.get_text(strip=True)

#                 if col_name is None:
#                     col_name = f"col_{j}"

#                 row_dict[col_name] = text

#             if row_dict:
#                 rows_data.append(row_dict)

#         df = pd.DataFrame(rows_data)

#         df = df.replace("", pd.NA)
#         df = df.dropna(thresh=df.shape[1] / 2)

#         df["year"] = year

#         if table_name is None:
#             table_name = f"table_{i}"

#             if table_name == "table_0" and df.shape[0] == 5:
#                 table_name = "past_5_games"
#             elif table_name == "table_3" and df.shape[0] == 7:
#                 table_name = "stathead_insight"

#         tables[table_name] = df
        
#     df = df.dropna(axis=1, how='all')

#     draft_data.append(df)

#     time.sleep(np.random.randint(5, 15))

# draft_data = pd.concat(draft_data)

# with sqlite3.connect('nba.db', timeout=60) as conn:
#     draft_data.to_sql(
#         'draft_stats',
#         conn,
#         if_exists='replace',
#         index=False
#     )

In [34]:
with sqlite3.connect('nba.db') as conn:
    draft_stats = pd.read_sql_query(
        'SELECT * FROM "draft_stats"',
        conn
    )

draft_stats = draft_stats[draft_stats['player'] != 'Player'].reset_index(drop=True)

draft_stats.head()

,ranker,pick_overall,team_id,player,college_name,seasons,g,mp,pts,trb,...,ft_pct,mp_per_g,pts_per_g,trb_per_g,ast_per_g,ws,ws_per_48,bpm,vorp,year
0,1,1,MIN,Karl-Anthony Towns,Kentucky,11,720,24294,16384,8025,...,.840,33.7,22.8,11.1,3.1,94.6,.187,4.3,38.5,2015
1,2,2,LAL,D'Angelo Russell,Ohio State,11,655,19240,11132,2177,...,.793,29.4,17.0,3.3,5.6,26.5,.066,0.6,12.4,2015
2,3,3,PHI,Jahlil Okafor,Duke,7,248,4830,2566,1170,...,.676,19.5,10.3,4.7,0.9,7.2,.071,-2.0,0.0,2015
3,4,4,NYK,Kristaps Porziņģis,NaN,10,533,16175,10372,4055,...,.830,30.3,19.5,7.6,1.9,50.4,.150,2.6,18.9,2015
4,5,5,ORL,Mario Hezonja,NaN,5,330,6107,2284,1026,...,.812,18.5,6.9,3.1,1.3,3.2,.025,-2.8,-1.2,2015

---
### Data Wrangling
---

In [7]:
ncaa_stats.head()

,season,seasonLabel,teamId,team,conference,athleteId,athleteSourceId,name,position,games,...,freeThrows_attempted,freeThrows_pct,rebounds_offensive,rebounds_defensive,rebounds_total,winShares_offensive,winShares_defensive,winShares_total,winShares_totalPer40,year
0,2015,20142015,1,Abilene Christian,Southland,47237,3152345,K.J. Maura,G,17,...,5,100.0,7,17,24,0.1,0.1,0.2,0.041,2015
1,2015,20142015,1,Abilene Christian,Southland,47386,3152349,Drake Green,G,28,...,16,56.3,4,18,22,-0.4,0.1,-0.3,-0.049,2015
2,2015,20142015,1,Abilene Christian,Southland,47387,3152347,Isaiah Tripp,G,29,...,25,60.0,13,20,33,0.2,0.1,0.3,0.057,2015
3,2015,20142015,1,Abilene Christian,Southland,52198,67296,Christian Albright,F,20,...,17,64.7,21,44,65,-0.2,0.3,0.1,0.015,2015
4,2015,20142015,1,Abilene Christian,Southland,56233,3155902,Duran Porter,F,31,...,40,50.0,29,42,71,-0.1,0.2,0.1,0.010,2015

In [ ]:
draft_stats['player'] = draft_stats['player'].str.strip() 

players = draft_stats['player'].to_list()

ncaa_stats['name'] = ncaa_stats['name'].str.strip()
df = ncaa_stats[ncaa_stats["name"].isin(players)]

draft_stats_target = draft_stats[[
    'player', 
    'pick_overall', 
    'team_id', 
    'vorp', 
    'bpm', 
    'ws_per_48', 
    'ws', 
    'year'
]]

# only using a player's last season in the ncaa
df = (
    df
    .drop(columns=['year'])
    .sort_values(['name', 'season'])
    .groupby('name')
    .tail(1)
    .reset_index(drop=True)
)

df = df.merge(draft_stats_target, left_on='name', right_on='player', how='left')

df = (
    df
    [df['season'] <= df['year']]
    .rename(columns={
        'year':'draft_year', 
        'vorp':'nba_vorp', 
        'bpm':'nba_bpm', 
        'ws_per_48':'nba_ws_per_48', 
        'ws':'nba_ws'}
    )
    .reset_index(drop=True)
)

df.columns

Index(['season', 'seasonLabel', 'teamId', 'team', 'conference', 'athleteId',
       'athleteSourceId', 'name', 'position', 'games', 'starts', 'minutes',
       'points', 'turnovers', 'fouls', 'assists', 'steals', 'blocks',
       'offensiveRating', 'defensiveRating', 'netRating', 'PORPAG', 'usage',
       'assistsTurnoverRatio', 'offensiveReboundPct', 'freeThrowRate',
       'effectiveFieldGoalPct', 'trueShootingPct', 'fieldGoals_made',
       'fieldGoals_attempted', 'fieldGoals_pct', 'twoPointFieldGoals_made',
       'twoPointFieldGoals_attempted', 'twoPointFieldGoals_pct',
       'threePointFieldGoals_made', 'threePointFieldGoals_attempted',
       'threePointFieldGoals_pct', 'freeThrows_made', 'freeThrows_attempted',
       'freeThrows_pct', 'rebounds_offensive', 'rebounds_defensive',
       'rebounds_total', 'winShares_offensive', 'winShares_defensive',
       'winShares_total', 'winShares_totalPer40', 'player', 'pick_overall',
       'team_id', 'nba_vorp', 'nba_bpm', 'nba_ws_per_48', 'nba_ws',
       'draft_year'],
      dtype='str')

---
### Exploratory Data Analysis
---

In [53]:
player_info = {
    "Jalen Brunson":      [2018, "Villanova", "brunsja01"],
    "Chris Paul":         [2005, "Wake Forest", "paulch01"],
    "Fred VanVleet":      [2016, "Wichita State", "vanvlfr01"],
    "Kyle Lowry":         [2006, "Villanova", "lowryky01"],
    "Jrue Holiday":       [2009, "UCLA", "holidjr01"],
    "Mike Conley":        [2007, "Ohio State", "conlemi01"],
    "Davion Mitchell":    [2021, "Baylor", "mitchda01"],
    "Tyus Jones":         [2015, "Duke", "jonesty01"],
    "Jalen Suggs":        [2021, "Gonzaga", "suggsja01"],
    "Jamal Murray":       [2016, "Kentucky", "murraja01"],
    "Darius Garland":     [2019, "Vanderbilt", "garlada01"],
    "Mike Bibby":         [1998, "Arizona", "bibbymi01"],
    "Chauncey Billups":   [1997, "Colorado", "billuch01"],
    "Derek Fisher":       [1996, "Arkansas-Little Rock", "fishede01"],
    "Jalen Pickett":      [2023, "Penn State", "pickeja01"],
    "Darius Acuff Jr.":   [2026, "Arkansas", "acuffda01"], 
}

# for player, info in player_info.items():
#     print(f"Getting Player Info: {player}")

#     try:
#         scrape_functions.get_player_data(info[2])
#         time.sleep(np.random.randint(5, 15))

#         # scrape_functions.get_seasonal_stats(info[2])
#         # time.sleep(np.random.randint(5, 15))

#         print('Success')
#     except:
#         print(f'Player Failed: {player}')
#         continue

In [50]:
ids = [item[2] for item in player_info.values()]
years = [item[0] for item in player_info.values()]


with sqlite3.connect('nba.db') as conn:
    data = pd.read_sql_query(
        'SELECT * FROM "per_game_stats"',
        conn
    )

data = data.drop(columns=['awards'])
data = data[data['player'].isin(ids)] # take only players similar to daj

data['year_id'] = data['year_id'].str.slice(0, 4).astype(int) # convert year to integers

# keep only rookie years
data = data.sort_values(['player', 'year_id'])
data = data.drop_duplicates(subset=['player'], keep='first').reset_index(drop=True)

In [51]:
data

,year_id,age,team_name_abbr,comp_name_abbr,pos,games,games_started,mp_per_g,fg_per_g,fga_per_g,...,orb_per_g,drb_per_g,trb_per_g,ast_per_g,stl_per_g,blk_per_g,tov_per_g,pf_per_g,pts_per_g,player
0,1998,20,VAN,NBA,PG,50,50,35.2,5.2,12.1,...,0.6,2.1,2.7,6.5,1.6,0.1,2.9,2.4,13.2,bibbymi01
1,1997,21,2TM,NBA,PG,80,70,27.7,3.5,9.4,...,0.8,1.6,2.4,3.9,1.3,0.1,2.2,2.2,11.2,billuch01
2,2018,22,DAL,NBA,PG,73,38,21.8,3.6,7.7,...,0.3,2.0,2.3,3.2,0.5,0.1,1.2,1.7,9.3,brunsja01
3,2007,20,MEM,NBA,PG,53,46,26.1,3.6,8.3,...,0.4,2.2,2.6,4.2,0.8,0.0,1.7,1.6,9.4,conlemi01
4,1996,22,LAL,NBA,PG,80,3,11.5,1.3,3.3,...,0.3,0.9,1.2,1.5,0.5,0.1,0.9,1.1,3.9,fishede01
5,2019,20,CLE,NBA,SG,59,59,30.9,4.7,11.8,...,0.5,1.4,1.9,3.9,0.7,0.1,2.6,1.6,12.3,garlada01
6,2009,19,PHI,NBA,PG,73,51,24.2,3.2,7.1,...,0.8,1.8,2.6,3.8,1.1,0.2,2.1,2.1,8.0,holidjr01
7,2015,19,MIN,NBA,PG,37,0,15.5,1.5,4.2,...,0.2,1.1,1.3,2.9,0.8,0.1,0.9,0.9,4.2,jonesty01
8,2006,20,MEM,NBA,PG,10,0,17.5,1.4,3.8,...,1.2,1.9,3.1,3.2,1.4,0.1,1.2,2.0,5.6,lowryky01
9,2021,23,SAC,NBA,PG,75,19,27.7,4.7,11.2,...,0.4,1.8,2.2,4.2,0.7,0.3,1.5,1.9,11.5,mitchda01
10,2016,19,DEN,NBA,SG,82,10,21.5,3.6,8.9,...,0.5,2.1,2.6,2.1,0.6,0.3,1.4,1.5,9.9,murraja01
11,2005,20,NOK,NBA,PG,78,78,36.0,5.2,12.1,...,0.8,4.3,5.1,7.8,2.2,0.1,2.3,2.8,16.1,paulch01
12,2021,24,DET,NBA,PF,13,0,13.5,1.4,3.8,...,0.5,2.0,2.5,0.5,0.0,0.5,0.4,0.9,3.8,pickeja01
13,2021,20,ORL,NBA,PG,48,45,27.2,4.1,11.4,...,0.5,3.0,3.6,4.4,1.2,0.4,3.0,3.0,11.8,suggsja01
14,2016,22,TOR,NBA,PG,37,0,7.9,1.1,3.0,...,0.1,1.0,1.1,0.9,0.4,0.1,0.4,1.0,2.9,vanvlfr01